env: JRUBY_OPTS=--debug
language: ruby

cache:
  bundler: true

before_install:
  - gem update --system
  - gem install bundler

script:
  - make test

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
  - jruby-9.2.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
